automation:
  #turn on bedroom after 20 PM with movement till 00AM
  - alias: Turn on bedroom light after 20 PM with movement
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d00010ef41a
        to: 'on'
    condition:
      - condition: time
        after: '20:00:00'
        before: '00:00:00'
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: light.yeelight_rgb_f0b429b7deef
          color_temp: 154
          brightness: 80
  #turn on bedroom after 20 PM with movement
  - alias: Turn on bedroom light after 00 PM with movement
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d00010ef41a
        to: 'on'
    condition:
      - condition: time
        after: '00:00:00'
        before: '08:00:00'
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: light.yeelight_rgb_f0b429b7deef
          color_temp: 401
          brightness: 20

#windows open with cold or rain
  - alias: windows open with cold or rain
    trigger:
      - platform: state
        entity_id: sensor.yr_symbol
        to: '10'
      - platform: state
        entity_id: sensor.yr_symbol
        to: '46'
    condition:
      - condition: state
        entity_id: binary_sensor.door_window_sensor_158d00010e4109
        state: 'on'
    action:
      - service: notify.my_pushbullet
        data:
          message: "Close My bedroom window it´s raining"

#windows open after 21
  - alias: windows open after 21:00
    trigger:
      - platform: time
        at: '21:00:00'
    condition:
      - condition: state
        entity_id: binary_sensor.door_window_sensor_158d00010e4109
        state: 'on'
    action:
      - service: notify.my_pushbullet
        data:
          message: "Close My bedroom window it pass 21 Hours"

#turn off bedroom light when after 3 minutes was no movemnt
  - alias: Turn off bedroom light no movement
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d00010ef41a
        to: 'off'
        for:
          minutes: 1
    action:
      - service: homeassistant.turn_off
        entity_id: light.yeelight_rgb_f0b429b7deef

group:
  my_bedroom:
    name: My bedroom
    entities:
      - binary_sensor.door_window_sensor_158d00010e4109
      - binary_sensor.motion_sensor_158d00010ef41a
      - light.yeelight_rgb_f0b429b7deef
      - sensor.humidity_158d000114322c
      - sensor.temperature_158d000114322c
